add_newline = false
[package]
disabled = true

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ](bold yellow)"
vicmd_symbol = "[ï†”](bold blue)"

[git_status]
modified = "[ï„](green) "
deleted = "[ï€”](yellow) "
untracked = "[ïŠœ](white) "

[time]
disabled = true
use_12hr = true
format = 'ğŸ•™[$time]($style) '
time_format = "%l:%M"

[battery]
[[battery.display]]
threshold = 20
